// <auto-generated />
using CMS5.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CMS5.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20201118170130_Create")]
    partial class Create
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("CMS5.Models.Student", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Major")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Students");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "5@5amcn.com",
                            Major = 1,
                            Name = "周龙"
                        },
                        new
                        {
                            Id = 2,
                            Email = "zs@5amcn.com",
                            Major = 3,
                            Name = "张三"
                        },
                        new
                        {
                            Id = 3,
                            Email = "ls@5amcn.com",
                            Major = 2,
                            Name = "李四"
                        },
                        new
                        {
                            Id = 4,
                            Email = "ww@5amcn.com",
                            Major = 2,
                            Name = "王五"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
